import requests, os, time
def gr():
    os.system("color 0a") # green
def p(p):
    print(f"[+] {p}")
def run(c):
    p(f"Running command: {c}")
    os.system(c)

gr()
p("INDEPENDENT - An app to download ependencies for Roblox Exploits. Lightweight, fast.")
p("https://github.com/skidsploiter/dependent")
p("Welcome!")
print()
p("Installing Node.js...")
run("winget install --id=Schniz.fnm  -e")
run("fnm env --use-on-cd | Out-String | Invoke-Expression")
run("fnm use --install-if-missing 22")
p("Checking Node & NPM Version..")
p("node:")
run("node -v")
p("npm:")
run("npm -v")
print("\n")
p("Successfully installed Node.js!")
gr()
input("Press enter to continue...  ")
print()
p("Installing .NET 8.0...")
run("winget install Microsoft.DotNet.SDK.8")
p("Installed .NET 8.0!")
gr()
input("Press enter to continue...   ")
p("Installing WebView2...")
run("winget install --id=Microsoft.EdgeWebView2Runtime  -e")
p("Installed.")
gr()
p("Goodbye!")
input("Press ENTER to exit...    ")
